name: Build Flashable Zip
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Magisk Module Zip
        run: |
          zip -r Neural-Governor.zip module.prop customize.sh system README.md
      - uses: actions/upload-artifact@v4
        with:
          name: Neural-Governor-zip
          path: Neural-Governor.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Neural-Governor.zip
